### ISSUE TITLE
如何解耦本地资源投屏，自己能否直接拼接本地视频地址？

### ISSUE THREAD

**Issue by hiliving** [lzan13/VMScreenCast#2]
本地投屏有点繁琐，是否可以自己用一个文件选择器，取到视频文件路径后，自己拼接出投屏链接？该怎么设置呢

**Comment by lzan13** [comment]
这个好像是不行的，并不是一个链接，是需要创建一个本地服务，然后供投屏设备进行访问，就好比你有一个 html，拼接一个访问地址，但是你不把他部署到服务器上怎么访问呢？

**Comment by hiliving** [comment]
谢谢楼主回复，问题解决了，本地服务器扫描出的文件列表可以根据路径筛选出当前文件对应链接。
